### ISSUE TITLE
HTMX indicator style is addded to the head everytime I navigate

### ISSUE THREAD

**Issue by pravnkay** [mauricius/laravel-htmx#22]
I am using the following setup

- Laravel
- HTMX
- Packages
  - nWidart/laravel-modules
  - lorisleiva/laravel-actions
- Bootstrap for CSS

I am using `hx-boost` on the body tag and `@fragment` from laravel blade just under the body tag and nested layouts.
Here is the sample of my `layout.blade.php`

```php
<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="The description of the website">

	<link rel="stylesheet" href="{{asset('assets/css/theme/light.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/custom/skeleton.css')}}">

	<title>Laravel + HTMX</title>

</head>
<body hx-boost="true">
@fragment('HX')

	@include('core::layouts.main.includes.header')

	@include('core::layouts.main.includes.nav-slider')
	
	<section class="content-area">
		@include('core::layouts.main.includes.nav-sidebar')
		<div class="main-content gx-5">
			<div class="main-content-inner">
				@yield('main-content')
			</div>
		</div>
	</section>

	@include('core::layouts.main.includes.alert')

	<script src="{{asset('assets/libs/htmx/htmx2.0.2.min.js')}}"></script>
	<script src="{{asset('assets/libs/bootstrap5/js/bootstrap.bundle.min.js')}}"></script>

	@stack('page-scripts')
@endfragment
</body>
</html>
```
And whenever I navigate, I am getting this style tag added to my `<head>`

```css
<style>  .htmx-indicator{opacity:0}      .htmx-request .htmx-indicator{opacity:1; transition: opacity 200ms ease-in;}      .htmx-request.htmx-indicator{opacity:1; transition: opacity 200ms ease-in;}</style>
```
